/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1f6055cad97383611d231edacb8faa25)
interface __BaseEnv_Env {
	MINIMAX_MODEL: "MiniMax-M2.7";
	ALLOWED_ORIGINS: "https://christopher-portfolio93.web.app,https://topher1993.github.io,http://127.0.0.1:8085,http://localhost:8085";
	MINIMAX_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MINIMAX_MODEL" | "ALLOWED_ORIGINS" | "MINIMAX_API_KEY">> {}
}
